-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module OnlineOps.Object.Space exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import OnlineOps.InputObject
import OnlineOps.Interface
import OnlineOps.Object
import OnlineOps.Scalar
import OnlineOps.ScalarCodecs
import OnlineOps.Union


id : SelectionSet OnlineOps.ScalarCodecs.Id OnlineOps.Object.Space
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (OnlineOps.ScalarCodecs.codecs |> OnlineOps.Scalar.unwrapCodecs |> .codecId |> .decoder)


insertedAt : SelectionSet OnlineOps.ScalarCodecs.Timestamp OnlineOps.Object.Space
insertedAt =
    Object.selectionForField "ScalarCodecs.Timestamp" "insertedAt" [] (OnlineOps.ScalarCodecs.codecs |> OnlineOps.Scalar.unwrapCodecs |> .codecTimestamp |> .decoder)


name : SelectionSet (Maybe String) OnlineOps.Object.Space
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet OnlineOps.ScalarCodecs.Timestamp OnlineOps.Object.Space
updatedAt =
    Object.selectionForField "ScalarCodecs.Timestamp" "updatedAt" [] (OnlineOps.ScalarCodecs.codecs |> OnlineOps.Scalar.unwrapCodecs |> .codecTimestamp |> .decoder)
