-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.OnlineOps.Object.Space exposing (..)

import Api.OnlineOps.InputObject
import Api.OnlineOps.Interface
import Api.OnlineOps.Object
import Api.OnlineOps.Scalar
import Api.OnlineOps.ScalarCodecs
import Api.OnlineOps.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Api.OnlineOps.ScalarCodecs.Id Api.OnlineOps.Object.Space
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.OnlineOps.ScalarCodecs.codecs |> Api.OnlineOps.Scalar.unwrapCodecs |> .codecId |> .decoder)


insertedAt : SelectionSet Api.OnlineOps.ScalarCodecs.Timestamp Api.OnlineOps.Object.Space
insertedAt =
    Object.selectionForField "ScalarCodecs.Timestamp" "insertedAt" [] (Api.OnlineOps.ScalarCodecs.codecs |> Api.OnlineOps.Scalar.unwrapCodecs |> .codecTimestamp |> .decoder)


name : SelectionSet (Maybe String) Api.OnlineOps.Object.Space
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet Api.OnlineOps.ScalarCodecs.Timestamp Api.OnlineOps.Object.Space
updatedAt =
    Object.selectionForField "ScalarCodecs.Timestamp" "updatedAt" [] (Api.OnlineOps.ScalarCodecs.codecs |> Api.OnlineOps.Scalar.unwrapCodecs |> .codecTimestamp |> .decoder)
