-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.OnlineOps.Object.UserAuth exposing (..)

import Api.OnlineOps.InputObject
import Api.OnlineOps.Interface
import Api.OnlineOps.Object
import Api.OnlineOps.Scalar
import Api.OnlineOps.ScalarCodecs
import Api.OnlineOps.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


accessToken : SelectionSet String Api.OnlineOps.Object.UserAuth
accessToken =
    Object.selectionForField "String" "accessToken" [] Decode.string


user : SelectionSet decodesTo Api.OnlineOps.Object.UserProfile -> SelectionSet decodesTo Api.OnlineOps.Object.UserAuth
user object_ =
    Object.selectionForCompositeField "user" [] object_ identity
