-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module OnlineOps.Object.UserAuth exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import OnlineOps.InputObject
import OnlineOps.Interface
import OnlineOps.Object
import OnlineOps.Scalar
import OnlineOps.ScalarCodecs
import OnlineOps.Union


accessToken : SelectionSet String OnlineOps.Object.UserAuth
accessToken =
    Object.selectionForField "String" "accessToken" [] Decode.string


user : SelectionSet decodesTo OnlineOps.Object.UserProfile -> SelectionSet decodesTo OnlineOps.Object.UserAuth
user object_ =
    Object.selectionForCompositeField "user" [] object_ identity
