-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module OnlineOps.Object.UserProfile exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import OnlineOps.InputObject
import OnlineOps.Interface
import OnlineOps.Object
import OnlineOps.Scalar
import OnlineOps.ScalarCodecs
import OnlineOps.Union


email : SelectionSet String OnlineOps.Object.UserProfile
email =
    Object.selectionForField "String" "email" [] Decode.string


firstName : SelectionSet String OnlineOps.Object.UserProfile
firstName =
    Object.selectionForField "String" "firstName" [] Decode.string


lastName : SelectionSet String OnlineOps.Object.UserProfile
lastName =
    Object.selectionForField "String" "lastName" [] Decode.string
