-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.OnlineOps.Object exposing (..)


type ConnectAccount
    = ConnectAccount


type ConnectProperty
    = ConnectProperty


type ConnectView
    = ConnectView


type SetupOption
    = SetupOption


type Space
    = Space


type SpacePayload
    = SpacePayload


type StepPayload
    = StepPayload


type UserAuth
    = UserAuth


type UserAuthPayload
    = UserAuthPayload


type UserPayload
    = UserPayload


type UserProfile
    = UserProfile


type ValidationMessage
    = ValidationMessage


type ValidationOption
    = ValidationOption
