-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.OnlineOps.ScalarCodecs exposing (..)

import Api.OnlineOps.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    Api.OnlineOps.Scalar.Id


type alias Timestamp =
    Api.OnlineOps.Scalar.Timestamp


codecs : Api.OnlineOps.Scalar.Codecs Id Timestamp
codecs =
    Api.OnlineOps.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecTimestamp = defaultCodecs.codecTimestamp
        }
