-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module OnlineOps.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import OnlineOps.Scalar exposing (defaultCodecs)


type alias Id =
    OnlineOps.Scalar.Id


type alias Timestamp =
    OnlineOps.Scalar.Timestamp


codecs : OnlineOps.Scalar.Codecs Id Timestamp
codecs =
    OnlineOps.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecTimestamp = defaultCodecs.codecTimestamp
        }
